# -*- coding: utf-8 -*-
"""streamlite_housing data_dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f669ZHh6WwD7OGKF_4FuZ3-UusTMpDBn
"""

!pip install pyngrok

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# st.title("Housing Dashboard")
# 
# df = pd.read_csv("housing data.csv")
# 
# st.write(df.head())
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # (paste above code here)
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # Page
# st.set_page_config(page_title="Dashboard", layout="wide")
# st.title("📊 Housing data Dashboard")
# 
# # 🔥 Upload dataset INSIDE STREAMLIT
# uploaded_file = st.file_uploader("Upload your dataset", type=["csv"])
# 
# if uploaded_file is not None:
# 
#     # Read uploaded file
#     df = pd.read_csv(uploaded_file)
# 
#     # Show preview
#     st.subheader("Dataset Preview")
#     st.dataframe(df.head())
# 
#     # Select column
#     column = st.selectbox("Select column", df.columns)
# 
#     # Pie chart
#     st.subheader("Pie Chart")
#     pie = df[column].value_counts().head(10)
#     fig = px.pie(values=pie.values, names=pie.index)
#     st.plotly_chart(fig)
# 
#     # Scatter plot
#     st.subheader("Scatter Plot")
#     x = st.selectbox("X axis", df.columns)
#     y = st.selectbox("Y axis", df.columns)
# 
#     fig2 = px.scatter(df, x=x, y=y)
#     st.plotly_chart(fig2)
# 
# else:
#     st.warning("⚠️ Please upload your dataset")

!pip install streamlit pyngrok

# Import
from pyngrok import ngrok
import subprocess
import time

# Token set
ngrok.set_auth_token("3CB7viBKSCw1UHYXnTR0CM1c6Sj_5ybL1rR2HMWZictw9Vw97")

# Kill previous
!pkill streamlit

# Run streamlit app
process = subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port", "8501"]
)

# Wait
time.sleep(5)

# Public URL
public_url = ngrok.connect(8501)
print("Streamlit App URL:", public_url)