# -*- coding: utf-8 -*-
"""streamlite_housing data_dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f669ZHh6WwD7OGKF_4FuZ3-UusTMpDBn
"""

# Commented out IPython magic to ensure Python compatibility.
 
import streamlit as st
import pandas as pd
st.title("Housing Dashboard")
df = pd.read_csv("housing data.csv")
st.write(df.head())


 #Commented out IPython magic to ensure Python compatibility.
 
import streamlit as st
import pandas as pd
import plotly.express as px
 
 # Page
st.set_page_config(page_title="Housing Dashboard", layout="wide")
st.title("📊 Housing data Dashboard")
 
  #🔥 Upload dataset INSIDE STREAMLIT
uploaded_file = st.file_uploader("chooe a CSV file", type=["csv"])
 
 # uploaded_file is not None:
if uploaded_file is not None:
     # Read uploaded file
 df = pd.read_csv(uploaded_file)
 st.success("file uploaded sucessfully!")
     # Show preview
 st.subheader("Dataset Preview")
 st.dataframe(df.head())
else:
 st.warning("upload a CSV file")
 st.info("otherwise it can be use the housing data")
 df=pd.read_csv("housing data.csv")
 st.dataframe(df)
 
     # Select column
column = st.selectbox("Select column", df.columns)
 
     # Pie chart
st.subheader("Pie Chart")
pie = df[column].value_counts().head(10)
fig = px.pie(values=pie.values, names=pie.index)
st.plotly_chart(fig)
 
     # Scatter plot
st.subheader("Scatter Plot")
x = st.selectbox("X axis", df.columns)
y = st.selectbox("Y axis", df.columns)
 
fig2 = px.scatter(df, x=x, y=y)
st.plotly_chart(fig2)
 
st.warning(" Please upload your dataset")

# Import

import subprocess
import time
# Run streamlit app
process = subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port", "8501"]
)
time.sleep(5)